<? php
if($_POST["message"]) {
  mail("your@email.address", "Here is the subject line",
  $_POST["insert your message here"]. "From: an@email.address");
}
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>Positive Kirby</title>';
echo '<meta charset="UTF-8">';
echo '<link rel="stylesheet" href="../CSS/style.css">';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '<meta content="" name="keywords">';
echo '<meta content="" name="description">';
echo '<!-- JavaScript Files-->';
echo '<script src="lib/jquery/jquery.min.js"></script>';
echo '<script src="lib/jquery/jquery-migrate.min.js"></script>';
echo '<script src="lib/bootstrap/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/mobile-nav/mobile-nav.js"></script>';
echo '<script src="lib/wow/wow.min.js"></script>';
echo '<script src="lib/waypoints/waypoints.min.js"></script>';
echo '<script src="lib/counterup/counterup.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '<script src="lib/isotope/isotope.pkgd.min.js"></script>';
echo '<script src="lib/lightbox/js/lightbox.min.js"></script>';
echo '<!-- Contact Form JavaScript File -->';
echo '<script src="contactform/contactform.js"></script>';
echo '';
echo '<!-- Template Main Javascript File -->';
echo '<script src="js/main.js"></script>';
echo '<!-- Favicons -->';
echo '<link href="img/favicon.png" rel="icon">';
echo '<link href="img/apple-touch-icon.png" rel="apple-touch-icon">';
echo '';
echo '<!-- Google Fonts -->';
echo '<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">';
echo '';
echo '<!-- Bootstrap CSS File -->';
echo '<link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '<!-- Libraries CSS Files -->';
echo '<link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">';
echo '<link href="lib/animate/animate.min.css" rel="stylesheet">';
echo '<link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet">';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">';
echo '<link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">';
echo '</head>';
echo '<body>';
echo '<!--Header-->';
echo '<header id="header">';
echo '<div id="topbar">';
echo '<div class="container">';
echo '<div class="social-links">';
echo '<a href="https://www.facebook.com/Positive-Will-115149290235446" class="facebook"><i class="fa fa-facebook"></i></a>';
echo '<a href="https://www.instagram.com/positive_kirby/" class="instagram"><i class="fa fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '<div class="container">';
echo '';
echo '<div class="logo float-left">';
echo '<!-- Uncomment below if you prefer to use an image logo -->';
echo '<!--<h1 class="text-light"><a href="#intro" class="scrollto"><span><b>Positive</b>Will</span></a></h1>-->';
echo '<a href="#header" class="scrollto"><img src="../CSS/Images/Logotipo_principal.png" alt="" class="img-fluid"></a>';
echo '</div>';
echo '';
echo '<nav class="main-nav float-right d-none d-lg-block">';
echo '<ul>';
echo '<li class="active"><a href="#intro">Home</a></li>';
echo '<li><a href="#about">About Us</a></li>';
echo '<li><a href="#services">Services</a></li>';
echo '<li><a href="#footer">Contact Us</a></li>';
echo '</ul>';
echo '</nav><!-- .main-nav -->';
echo '</div>';
echo '</header><!-- #header -->';
echo '';
echo '<!--INTRO-->';
echo '<section id="intro" class="clearfix">';
echo '<div class="container d-flex h-100">';
echo '<div class="row justify-content-center align-self-center">';
echo '<div class="col-md-6 intro-info order-md-first order-last">';
echo '<h2>Criamos Valor e<br><span>Bem Estar</span></h2>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section><!-- #intro -->';
echo '';
echo '<!--==========================';
echo 'About Us Section';
echo '============================-->';
echo '<section id="about">';
echo '';
echo '<div class="container">';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-5 col-md-6">';
echo '<div class="about-img">';
echo '<img src="img/about-img.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-lg-7 col-md-6">';
echo '<div class="about-content">';
echo '<h2>About Us</h2>';
echo '<h3>Odio sed id eos et laboriosam consequatur eos earum soluta.</h3>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>';
echo '<p>Aut dolor id. Sint aliquam consequatur ex ex labore. Et quis qui dolor nulla dolores neque. Aspernatur consectetur omnis numquam quaerat. Sed fugiat nisi. Officiis veniam molestiae. Et vel ut quidem alias veritatis repudiandae ut fugit. Est ut eligendi aspernatur nulla voluptates veniam iusto vel quisquam. Fugit ut maxime incidunt accusantium totam repellendus eum error. Et repudiandae eum iste qui et ut ab alias.</p>';
echo '<ul>';
echo '<li><i class="ion-android-checkmark-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>';
echo '<li><i class="ion-android-checkmark-circle"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>';
echo '<li><i class="ion-android-checkmark-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</section><!-- #about -->';
echo '<!--==========================';
echo 'Services Section';
echo '============================-->';
echo '<section id="services" class="section-bg">';
echo '<div class="container">';
echo '';
echo '<header class="section-header">';
echo '<h3>Services</h3>';
echo '<p>Laudem latine persequeris id sed, ex fabulas delectus quo. No vel partiendo abhorreant vituperatoribus.</p>';
echo '</header>';
echo '';
echo '<div class="row">';
echo '';
echo '<div class="col-md-6 col-lg-4 wow bounceInUp" data-wow-duration="1.4s">';
echo '<div class="box">';
echo '<div class="icon" style="background: #fceef3;"><i class="ion-ios-analytics-outline" style="color: #ff689b;"></i></div>';
echo '<h4 class="title"><a href="">Lorem Ipsum</a></h4>';
echo '<p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4 wow bounceInUp" data-wow-duration="1.4s">';
echo '<div class="box">';
echo '<div class="icon" style="background: #fff0da;"><i class="ion-ios-bookmarks-outline" style="color: #e98e06;"></i></div>';
echo '<h4 class="title"><a href="">Dolor Sitema</a></h4>';
echo '<p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-6 col-lg-4 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">';
echo '<div class="box">';
echo '<div class="icon" style="background: #e6fdfc;"><i class="ion-ios-paper-outline" style="color: #3fcdc7;"></i></div>';
echo '<h4 class="title"><a href="">Sed ut perspiciatis</a></h4>';
echo '<p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">';
echo '<div class="box">';
echo '<div class="icon" style="background: #eafde7;"><i class="ion-ios-speedometer-outline" style="color:#41cf2e;"></i></div>';
echo '<h4 class="title"><a href="">Magni Dolores</a></h4>';
echo '<p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-6 col-lg-4 wow bounceInUp" data-wow-delay="0.2s" data-wow-duration="1.4s">';
echo '<div class="box">';
echo '<div class="icon" style="background: #e1eeff;"><i class="ion-ios-world-outline" style="color: #2282ff;"></i></div>';
echo '<h4 class="title"><a href="">Nemo Enim</a></h4>';
echo '<p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-6 col-lg-4 wow bounceInUp" data-wow-delay="0.2s" data-wow-duration="1.4s">';
echo '<div class="box">';
echo '<div class="icon" style="background: #ecebff;"><i class="ion-ios-clock-outline" style="color: #8660fe;"></i></div>';
echo '<h4 class="title"><a href="">Eiusmod Tempor</a></h4>';
echo '<p class="description">Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi</p>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</section><!-- #services -->';
echo '</main>';
echo '';
echo '<footer id="footer" class="section-bg">';
echo '<div class="footer-top">';
echo '<div class="container">';
echo '';
echo '<div class="row">';
echo '';
echo '<div class="col-lg-6">';
echo '';
echo '<div class="row">';
echo '';
echo '<div class="col-sm-6">';
echo '';
echo '<div class="footer-info">';
echo '<h3>Positive Will</h3>';
echo '<p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus. Scelerisque felis imperdiet proin fermentum leo. Amet volutpat consequat mauris nunc congue.</p>';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '<div class="col-sm-6">';
echo '<div class="footer-links">';
echo '<h4>Contact Us</h4>';
echo '<p>';
echo 'A108 Adam Street <br>';
echo 'New York, NY 535022<br>';
echo 'United States <br>';
echo '<strong>Phone:</strong> +1 5589 55488 55<br>';
echo '<strong>Email:</strong> info@example.com<br>';
echo '</p>';
echo '</div>';
echo '';
echo '<div class="social-links">';
echo '<a href="https://www.facebook.com/Positive-Will-115149290235446" class="facebook"><i class="fa fa-facebook"></i></a>';
echo '<a href="https://www.instagram.com/positive_kirby/" class="instagram"><i class="fa fa-instagram"></i></a>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="col-lg-6">';
echo '';
echo '<div class="form">';
echo '';
echo '<h4>Junta-te à equipa</h4>';
echo '<p>Eos ipsa est voluptates. Nostrum nam libero ipsa vero. Debitis quasi sit eaque numquam similique commodi harum aut temporibus.</p>';
echo '<form action="" method="post" role="form" class="contactForm">';
echo '<div class="form-group">';
echo '<input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />';
echo '<div class="validation"></div>';
echo '</div>';
echo '<div class="form-group">';
echo '<input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />';
echo '<div class="validation"></div>';
echo '</div>';
echo '<div class="form-group">';
echo '<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />';
echo '<div class="validation"></div>';
echo '</div>';
echo '<div class="form-group">';
echo '<textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>';
echo '<div class="validation"></div>';
echo '</div>';
echo '';
echo '<div id="sendmessage">Your message has been sent. Thank you!</div>';
echo '<div id="errormessage"></div>';
echo '';
echo '<div class="text-center"><button type="submit" title="Send Message">Send Message</button></div>';
echo '</form>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '</html>';
?>